### ISSUE TITLE
Iteration 1 - viewing sustainable alternatives

### ISSUE THREAD

**Issue by jacobandresen** [rufaidaju/class02-final-project#3]
**Week 1**
Produce a data model and SQL schemas based on the features listed above.

**Week 2**
Write a script that inserts data from JSON file provided by us into your data model.
Integrate the data model and API with a client-side application that provides browsing functionality. This can be search or just listing. Up to you.

**Task list for iteration 1:**
Database:
- [x] Create data model

NodeJS API:
- [ ] Load data from data.json into data model
- [ ] create api call to Load tag info from database
- [ ] create api call to Load category info from database
- [ ] extend api call to load category info sorted on metrics

React frontend:
- [ ] create UI to explore categories using tags .
